angular.module('Tienditas')
        .controller('DocCtrl', function ($scope) {

            $scope.examples = [
                "{{Complemento.ImpuestosLocales.RetencionesLocales.ImpLocRetenido}}",
                "{{Complemento.ImpuestosLocales.RetencionesLocales.Importe}}",
                "{{Complemento.ImpuestosLocales.RetencionesLocales.TasadeRetencion}}",
                "{{Complemento.ImpuestosLocales.TotaldeRetenciones}}",
                "{{Complemento.ImpuestosLocales.TotaldeTraslados}}",
                "{{Complemento.ImpuestosLocales.TrasladosLocales.ImpLocTrasladado}}",
                "{{Complemento.ImpuestosLocales.TrasladosLocales.Importe}}",
                "{{Complemento.ImpuestosLocales.TrasladosLocales.TasadeTraslado}}",
                "{{Complemento.ImpuestosLocales.version}}",
                "{{Complemento.TimbreFiscalDigital.FechaTimbrado}}",
                "{{Complemento.TimbreFiscalDigital.noCertificadoSAT}}",
                "{{Complemento.TimbreFiscalDigital.selloCFD}}",
                "{{Complemento.TimbreFiscalDigital.selloSAT}}",
                "{{Complemento.TimbreFiscalDigital.UUID}}",
                "{{Complemento.TimbreFiscalDigital.version}}",
                "{{Conceptos.Concepto.cantidad}}",
                "{{Conceptos.Concepto.descripcion}}",
                "{{Conceptos.Concepto.importe}}",
                "{{Conceptos.Concepto.unidad}}",
                "{{Conceptos.Concepto.valorUnitario}}",
                "{{condicionesDePago}}",
                "{{descuento}}",
                "{{Emisor.DomicilioFiscal.calle}}",
                "{{Emisor.DomicilioFiscal.codigoPostal}}",
                "{{Emisor.DomicilioFiscal.colonia}}",
                "{{Emisor.DomicilioFiscal.estado}}",
                "{{Emisor.DomicilioFiscal.localidad}}",
                "{{Emisor.DomicilioFiscal.municipio}}",
                "{{Emisor.DomicilioFiscal.noExterior}}",
                "{{Emisor.DomicilioFiscal.noInterior}}",
                "{{Emisor.DomicilioFiscal.pais}}",
                "{{Emisor.nombre}}",
                "{{Emisor.RegimenFiscal.0.Regimen}}",
                "{{Emisor.rfc}}",
                "{{fecha}}",
                "{{folio}}",
                "{{formaDePago}}",
                "{{Impuestos.Retenciones.Retencion.importe}}",
                "{{Impuestos.Retenciones.Retencion.impuesto}}",
                "{{Impuestos.totalImpuestosRetenidos}}",
                "{{Impuestos.totalImpuestosTrasladados}}",
                "{{Impuestos.Traslados.Traslado.importe}}",
                "{{Impuestos.Traslados.Traslado.impuesto}}",
                "{{Impuestos.Traslados.Traslado.tasa}}",
                "{{LugarExpedicion}}",
                "{{metodoDePago}}",
                "{{Moneda}}",
                "{{motivoDescuento}}",
                "{{noCertificado}}",
                "{{NumCtaPago}}",
                "{{originalString}}",
                "{{originalStringTFD}}",
                "{{Receptor.Domicilio.calle}}",
                "{{Receptor.Domicilio.codigoPostal}}",
                "{{Receptor.Domicilio.colonia}}",
                "{{Receptor.Domicilio.estado}}",
                "{{Receptor.Domicilio.localidad}}",
                "{{Receptor.Domicilio.municipio}}",
                "{{Receptor.Domicilio.noExterior}}",
                "{{Receptor.Domicilio.noInterior}}",
                "{{Receptor.Domicilio.pais}}",
                "{{Receptor.nombre}}",
                "{{Receptor.rfc}}",
                "{{sello}}",
                "{{serie}}",
                "{{subTotal}}",
                "{{TipoCambio}}",
                "{{tipoDeComprobante}}",
                "{{total}}",
                "{{version}}"
            ];

//            $scope.highlight = function (text, search) {
//                if (!search) {
//                    return $sce.trustAsHtml(text);
//                }
//                return $sce.trustAsHtml(text.replace(new RegExp(search, 'gi'), '<span class="highlightedText">$&</span>'));
//            };
        });